language: python
python:
  - 3.7
branches:
  only:
    - master

install:
  - pip install numpy --upgrade
  - pip install --upgrade cython
  - pip install -r requirements.txt
  # - pip install tensorflow
  # - pip install word2vec
  # - pip install codecov

script:
  - cd 机器学习写诗/poet_master
  - python main.py 2
  # - python ./规则写诗/poetize.py
  # - python ./机器学习写诗/lyrics_writer/main.py 1 -cd modern
